import uuid
import json
from typing import Dict, Any, List, Optional
from datetime import datetime
from backend.database import get_db
from backend.services.ai_service import ai_service
from backend.services.competency_service import recalculate_user_competencies

def create_quiz_with_ai(
    user_id: str,
    topic: str,
    document_id: Optional[str] = None,
    course_id: Optional[str] = None,
    difficulty: str = "Medium",
    question_count: int = 5,
    question_type: str = "mcq",
    title: Optional[str] = None
) -> Dict[str, Any]:
    doc_text = None
    doc_title = None
    
    with get_db() as conn:
        cursor = conn.cursor()
        
        if document_id:
            cursor.execute("SELECT * FROM documents WHERE id = ?", (document_id,))
            doc_row = cursor.fetchone()
            if doc_row:
                doc_title = doc_row["title"]
                # Fetch chunks
                cursor.execute("SELECT content FROM document_chunks WHERE document_id = ? ORDER BY chunk_index ASC LIMIT 5", (document_id,))
                chunks = [r["content"] for r in cursor.fetchall()]
                doc_text = "\n\n".join(chunks)
                if not topic:
                    topic = doc_title
                    
        if not topic:
            topic = "Core Fundamentals & Applied Concepts"
            
        # Find matching skill_id if exists
        cursor.execute("SELECT id FROM skills WHERE name LIKE ? OR category LIKE ? LIMIT 1", (f"%{topic}%", f"%{topic}%"))
        skill_row = cursor.fetchone()
        skill_id = skill_row["id"] if skill_row else None
        
        # Call AI Service
        generated_questions = ai_service.generate_quiz_questions(
            topic=topic,
            document_text=doc_text,
            difficulty=difficulty,
            question_count=question_count,
            question_type=question_type
        )
        
        quiz_id = str(uuid.uuid4())
        quiz_title = title or f"AI Assessment: {topic} ({difficulty})"
        quiz_desc = f"Dynamically generated {difficulty}-level assessment covering {topic}. Generated by SkillSphere AI."
        
        cursor.execute("""
            INSERT INTO quizzes (
                id, title, description, course_id, document_id, creator_id, skill_id,
                difficulty, total_questions, passing_percentage, time_limit_minutes, is_adaptive
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, 60.0, ?, 1)
        """, (
            quiz_id, quiz_title, quiz_desc, course_id, document_id, user_id, skill_id,
            difficulty, len(generated_questions), max(len(generated_questions) * 2, 5)
        ))
        
        saved_questions = []
        for q in generated_questions:
            q_id = str(uuid.uuid4())
            cursor.execute("""
                INSERT INTO questions (
                    id, quiz_id, question_text, question_type, options_json, correct_answer,
                    explanation, topic, difficulty, points
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                q_id, quiz_id, q["question_text"], q.get("question_type", "mcq"),
                json.dumps(q.get("options", [])), q["correct_answer"],
                q.get("explanation", "Accurate conceptual deduction."),
                q.get("topic", topic), q.get("difficulty", difficulty), q.get("points", 1)
            ))
            saved_questions.append({
                "id": q_id,
                "question_text": q["question_text"],
                "question_type": q.get("question_type", "mcq"),
                "options": q.get("options", []),
                "topic": q.get("topic", topic),
                "difficulty": q.get("difficulty", difficulty),
                "points": q.get("points", 1)
            })
            
    return {
        "id": quiz_id,
        "title": quiz_title,
        "description": quiz_desc,
        "topic": topic,
        "difficulty": difficulty,
        "total_questions": len(saved_questions),
        "time_limit_minutes": max(len(saved_questions) * 2, 5),
        "questions": saved_questions
    }

def get_quiz_details(quiz_id: str, include_answers: bool = False) -> Optional[Dict[str, Any]]:
    with get_db() as conn:
        cursor = conn.cursor()
        cursor.execute("SELECT * FROM quizzes WHERE id = ?", (quiz_id,))
        q_row = cursor.fetchone()
        if not q_row:
            return None
        quiz = dict(q_row)
        
        cursor.execute("SELECT * FROM questions WHERE quiz_id = ?", (quiz_id,))
        q_rows = cursor.fetchall()
        
        questions = []
        for r in q_rows:
            q_dict = dict(r)
            q_dict["options"] = json.loads(q_dict["options_json"]) if q_dict.get("options_json") else []
            if not include_answers:
                q_dict.pop("correct_answer", None)
                q_dict.pop("explanation", None)
            questions.append(q_dict)
            
        quiz["questions"] = questions
        return quiz

def evaluate_and_submit_quiz(
    user_id: str,
    quiz_id: str,
    submissions: List[Dict[str, str]], # [{"question_id": "...", "user_answer": "..."}]
    time_spent_seconds: int = 60
) -> Dict[str, Any]:
    with get_db() as conn:
        cursor = conn.cursor()
        
        cursor.execute("SELECT * FROM quizzes WHERE id = ?", (quiz_id,))
        quiz_row = cursor.fetchone()
        if not quiz_row:
            raise ValueError("Quiz not found")
        quiz = dict(quiz_row)
        
        cursor.execute("SELECT * FROM questions WHERE quiz_id = ?", (quiz_id,))
        questions = {r["id"]: dict(r) for r in cursor.fetchall()}
        
        attempt_id = str(uuid.uuid4())
        total_questions = len(questions)
        correct_count = 0
        wrong_count = 0
        total_points_awarded = 0
        
        detailed_answers = []
        weak_topics = set()
        strong_topics = set()
        
        sub_map = {s["question_id"]: s["user_answer"] for s in submissions}
        
        for q_id, q_data in questions.items():
            u_ans = sub_map.get(q_id, "").strip()
            corr_ans = q_data["correct_answer"].strip()
            
            # Smart answer matching (e.g. "A" vs "A) ...")
            is_corr = False
            if u_ans:
                if u_ans.lower() == corr_ans.lower():
                    is_corr = True
                elif len(u_ans) == 1 and corr_ans.upper().startswith(u_ans.upper()):
                    is_corr = True
                elif u_ans[:2] == corr_ans[:2]:
                    is_corr = True
                    
            pts = q_data.get("points", 1) if is_corr else 0
            if is_corr:
                correct_count += 1
                total_points_awarded += pts
                strong_topics.add(q_data.get("topic", "General"))
            else:
                wrong_count += 1
                weak_topics.add(q_data.get("topic", "General"))
                
            detailed_answers.append({
                "question_id": q_id,
                "question_text": q_data["question_text"],
                "options": json.loads(q_data["options_json"]),
                "user_answer": u_ans,
                "correct_answer": corr_ans,
                "explanation": q_data["explanation"],
                "is_correct": is_corr,
                "points_awarded": pts,
                "topic": q_data["topic"]
            })
            
        percentage = round((correct_count / total_questions * 100), 1) if total_questions > 0 else 0.0
        
        # Adaptive difficulty modifier feedback
        adaptive_level = "Medium"
        if percentage >= 80:
            adaptive_level = "Hard"
            adaptive_feedback = "🔥 Outstanding performance! SkillSphere AI has increased your next quiz difficulty to Hard."
        elif percentage < 50:
            adaptive_level = "Easy"
            adaptive_feedback = "📘 Identified review areas. SkillSphere AI has scheduled targeted revision and foundational modules."
        else:
            adaptive_feedback = "👍 Solid proficiency demonstrated! Keep building consistent streaks."
            
        # Recommendation message
        if weak_topics:
            rec_msg = f"Targeted practice recommended in: {', '.join(list(weak_topics)[:2])}."
        else:
            rec_msg = "Great mastery! Continue to capstone projects and advanced certifications."
            
        # 1. Record attempt first
        cursor.execute("""
            INSERT INTO quiz_attempts (
                id, user_id, quiz_id, score, percentage, total_questions, correct_count,
                wrong_count, time_spent_seconds, adaptive_level, status,
                weak_topics_json, strong_topics_json, recommendations_json
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'completed', ?, ?, ?)
        """, (
            attempt_id, user_id, quiz_id, total_points_awarded, percentage, total_questions,
            correct_count, wrong_count, time_spent_seconds, adaptive_level,
            json.dumps(list(weak_topics)), json.dumps(list(strong_topics)), json.dumps([rec_msg])
        ))
        
        # 2. Record individual answers
        for da in detailed_answers:
            ans_id = str(uuid.uuid4())
            cursor.execute("""
                INSERT INTO quiz_answers (id, attempt_id, question_id, user_answer, is_correct, points_awarded)
                VALUES (?, ?, ?, ?, ?, ?)
            """, (ans_id, attempt_id, da["question_id"], da["user_answer"], 1 if da["is_correct"] else 0, da["points_awarded"]))
        
        # Add XP points to profile
        xp_gain = correct_count * 20 + 50
        cursor.execute("""
            UPDATE profiles
            SET xp_points = xp_points + ?,
                last_activity_date = CURRENT_TIMESTAMP
            WHERE user_id = ?
        """, (xp_gain, user_id))
        
        # Award badges if applicable
        cursor.execute("SELECT COUNT(*) as count FROM quiz_attempts WHERE user_id = ?", (user_id,))
        attempt_count = cursor.fetchone()["count"]
        
        unlocked_badge = None
        if attempt_count == 1:
            badge_id = str(uuid.uuid4())
            cursor.execute("""
                INSERT OR IGNORE INTO achievements (id, user_id, badge_code, badge_name, badge_description, icon, points_xp)
                VALUES (?, ?, 'first_quiz', 'First Quiz Explorer', 'Completed your first AI-generated assessment', '🏆', 100)
            """, (badge_id, user_id))
            unlocked_badge = "First Quiz Explorer"
        elif attempt_count >= 5:
            badge_id = str(uuid.uuid4())
            cursor.execute("""
                INSERT OR IGNORE INTO achievements (id, user_id, badge_code, badge_name, badge_description, icon, points_xp)
                VALUES (?, ?, 'quiz_veteran', 'Assessment Veteran', 'Completed 5+ comprehensive assessments', '🧠', 250)
            """, (badge_id, user_id))
            
    # Trigger real-time recalculation of user competencies!
    updated_competencies = recalculate_user_competencies(user_id)
    
    return {
        "attempt_id": attempt_id,
        "quiz_id": quiz_id,
        "quiz_title": quiz["title"],
        "score": total_points_awarded,
        "percentage": percentage,
        "total_questions": total_questions,
        "correct_count": correct_count,
        "wrong_count": wrong_count,
        "time_spent_seconds": time_spent_seconds,
        "adaptive_level": adaptive_level,
        "adaptive_feedback": adaptive_feedback,
        "strong_areas": list(strong_topics),
        "weak_areas": list(weak_topics),
        "recommendation": rec_msg,
        "xp_earned": xp_gain,
        "unlocked_badge": unlocked_badge,
        "answers": detailed_answers,
        "updated_competencies": updated_competencies
    }
